---
# tasks file for roles/osp-instance-delete
- name: Fetch Instance Info
  os_server_info:
    server: "*"
    # filters:
    #   vm_state: active
  register: r_servers
# - debug:
#     msg: "{{ result.openstack_servers }}"
- name: Delete instances
  os_server:
    name: "{{ item.name }}"
    state: absent
  loop: "{{ r_servers }}"
