---
# tasks file for lb-tier
- name: DEbug hostvars
  debug:
    var:  hostvars[groups['apps'].0].ansible_facts 

- name: Install HAProxy support packages
  package:
    name: 
      #- httpie
      - haproxy
    state: latest
- name: enable HAProxy
  service:
    name: haproxy
    state: started
    enabled: yes
- name: configure haproxy
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg
  notify: restart HAproxy
