---

# tasks file for osp.servers
- name: Create new server instances and attaches them a network and passes metadata to the instance
  os_server:
    name: "{{ item.value.name }}"
    image: "{{ item.value.image }}"
    key_name: "{{ item.value.key_name }}"
    meta:
      group: "{{ item.value.meta.0.group }}" 
      deployment_name: "{{ item.value.meta.0.deployment_name }}" 
    flavor: "{{ item.value.flavor }}"
    security_groups: 
      - "{{ item.value.security_group }}"
    network: int_network
    #nics: undefined # not required. A list of networks to which the instance's interface should be attached. Networks may be referenced by net-id/net-name/port-id or port-name.,Also this accepts a string containing a list of (net/port)-(id/name) Eg: nics: "net-id=uuid-1,port-name=myport" Only one of network or nics should be supplied.
    userdata: |
      {% raw %}
      #!/bin/bash
      mkdir -p /home/cloud-user/.ssh
      echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDBTCYfp/LvJHpyMqZBeXoX/jHz/LB4yAeRBMYLf3V/kopcIetQQHYIkgW96LB9CmQABX9heoopsDK8tj5IZgz//dPqfYapm+S4mz8jIOFvIwmUle6iM2KdBvMGqIBKiURVoTwQZZMoWzZEqmaHFrRuNrZCDUJ8B3LmNBqp3UQtnYUuG2Vtg/q94Wqlv7nGiBJ/bT0HhPjrsFGXJs29F354rK3Xp9KeKO9RB2PYNgIJ22KFNOZ3IV67I5bd2uJQXHEuQYqAenHh/cIt1GicOVGHKr9RQOngz4093/tuVfiwhIyKZVWu4Xm3G8x6v9nyg4ifi5XSBNvXBCuXSdivv+yd" >>   /home/cloud-user/.ssh/autorized_keys
      chown cloud-user: /home/cloud-user/.ssh/autorized_keys
      chmod u=rw,go= /home/cloud-user/.ssh/autorized_keys
      {% endraw %}
  loop: "{{ osp_servers | dict2items }}"

- name: Add floating IP to Servers
  os_floating_ip:
    server: "{{ item.value.name }}"
    network: ext_network
  loop: "{{ osp_servers | dict2items }}"

- name: Wait for server to be available
  wait_for:
    timeout: 600
    port: 22
