---
# tasks file for base-config
- name: pull repo file from local site into /etc
  become: yes
  become_user: root
  get_url:
      dest: /etc/yum.repos.d/internal.repo
      url: http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo